version: "3.8"

services:

  postgres:
    image: postgres:16
    container_name: copetran_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: copetran_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bus-net

  backend:
    build: .
    container_name: copetran_backend
    depends_on:
      - postgres
    ports:
      - "8083:8080"
    networks:
      - bus-net

volumes:
  postgres_data:

networks:
  bus-net: