spring.application.name=Copetran-project

spring.datasource.url=jdbc:postgresql://postgres:5432/copetran_db
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=false

# JWT Configuration
security.jwt.secret=1234abcd
security.jwt.expiration-seconds=3600
security.jwt.refresh-expiration-seconds=2592000